# Generated by Django 4.2.7 on 2023-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_author_post_date_post_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
    ]
